# Copied from original nix-basic/hardware-configuration.nix
# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e522e40-0da0-4c88-b1ee-46072b963684";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A18D-41E6";
      fsType = "vfat";
    };

  fileSystems."/mnt/media" =
    {
      device = "/dev/disk/by-uuid/39020e54-3574-47ed-a424-1ab37641b354";
      fsType = "ext4";
    };
    
  swapDevices =
    [ { device = "/dev/disk/by-uuid/9ea584ee-d806-4fae-9e9a-8067faa188b4"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

# For CI Testing, uncomment this instead:
# { config, lib, pkgs, modulesPath, ... }:
# 
# {
#   imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
# 
#   boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
#   boot.initrd.kernelModules = [ ];
#   boot.kernelModules = [ "kvm-amd" ];
#   boot.extraModulePackages = [ ];
# 
#   fileSystems."/" = {
#     device = "none";
#     fsType = "tmpfs";
#   };
# 
#   fileSystems."/boot" = {
#     device = "none";
#     fsType = "tmpfs";
#   };
# 
#   fileSystems."/media" = {
#     device = "none";
#     fsType = "tmpfs";
#     options = [ "defaults" "nofail" ];
#   };
# 
#   swapDevices = [ ];
# 
#   networking.useDHCP = lib.mkDefault true;
#   networking.hostId = "00000000"; # Required for ZFS
#   hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
# }