name: NixOS Configuration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Nix flake
        run: |
          nix flake check --impure

  home-manager-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check home-manager configuration
        run: |
          nix build .#homeConfigurations.chromeos.activationPackage --impure

  nixos-desktop-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dry-run NixOS desktop build
        run: |
          nix build .#nixosConfigurations.desktop.config.system.build.toplevel --impure