name: NixOS Configuration Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with debug logging'
        required: false
        default: false

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      
      - name: Validate flake
        run: nix flake show
  
  nixos-desktop-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      
      - name: Build desktop configuration (dry-run)
        run: |
          # This is a dry-run build that doesn't require root privileges
          nix build .#nixosConfigurations.desktop.config.system.build.toplevel --dry-run --allow-import-from-derivation
  
  nixos-server-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      
      - name: Build server configuration (dry-run)
        run: |
          # This is a dry-run build that doesn't require root privileges
          nix build .#nixosConfigurations.server.config.system.build.toplevel --dry-run --allow-import-from-derivation
          
  # Temporarily disable Darwin test until we have a full macOS config
  # darwin-dry-run:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     
  #     - name: Install Nix
  #       uses: cachix/install-nix-action@v31
  #       with:
  #         nix_path: nixpkgs=channel:nixos-unstable
  #         extra_nix_config: |
  #           experimental-features = nix-command flakes
  #           accept-flake-config = true
  #     
  #     - name: Build macOS configuration (dry-run)
  #       run: |
  #         # This is a dry-run build for macOS configuration
  #         nix build .#darwinConfigurations.macbook.system --dry-run